# One-shot generator for fixtures/synthetic/arcs_prechorded.gcode.
# Replicates klippy/extras/gcode_arcs.py planArc() (resolution 1.0)
# over the arcs in arcs_ij.gcode so the two fixtures trace the same
# toolpath. Not part of the build; kept out of the repo.
import math

MM_PER_ARC_SEGMENT = 1.0


def plan_arc(cur, target, offset, clockwise, as_e, as_f, absolute_extrude):
    # axes: XY plane -> alpha=0, beta=1, helical=2
    r_p = -offset[0]
    r_q = -offset[1]
    center_p = cur[0] - r_p
    center_q = cur[1] - r_q
    rt_alpha = target[0] - center_p
    rt_beta = target[1] - center_q
    angular_travel = math.atan2(r_p * rt_beta - r_q * rt_alpha,
                                r_p * rt_alpha + r_q * rt_beta)
    if angular_travel < 0.:
        angular_travel += 2. * math.pi
    if clockwise:
        angular_travel -= 2. * math.pi
    if (angular_travel == 0. and cur[0] == target[0] and cur[1] == target[1]):
        angular_travel = 2. * math.pi
    linear_travel = target[2] - cur[2]
    radius = math.hypot(r_p, r_q)
    flat_mm = radius * angular_travel
    if linear_travel:
        mm_of_travel = math.hypot(flat_mm, linear_travel)
    else:
        mm_of_travel = math.fabs(flat_mm)
    segments = max(1., math.floor(mm_of_travel / MM_PER_ARC_SEGMENT))
    theta_per_segment = angular_travel / segments
    linear_per_segment = linear_travel / segments
    e_per_move = e_base = 0.
    if as_e is not None:
        if absolute_extrude:
            e_base = cur[3]
        e_per_move = (as_e - e_base) / segments
    lines = []
    for i in range(1, int(segments) + 1):
        dist_helical = i * linear_per_segment
        c_theta = i * theta_per_segment
        cos_ti = math.cos(c_theta)
        sin_ti = math.sin(c_theta)
        r_pi = -offset[0] * cos_ti + offset[1] * sin_ti
        r_qi = -offset[0] * sin_ti - offset[1] * cos_ti
        c = [center_p + r_pi, center_q + r_qi, cur[2] + dist_helical]
        if i == segments:
            c = list(target)
        words = ["G1", "X" + repr(c[0]), "Y" + repr(c[1]), "Z" + repr(c[2])]
        if e_per_move:
            e_val = e_base + e_per_move
            words.append("E" + repr(e_val))
            if absolute_extrude:
                e_base = e_val
        if as_f is not None:
            words.append("F" + repr(as_f))
        lines.append(" ".join(words))
    return lines, list(target) + [as_e if as_e is not None else cur[3]]


out = [
    "; Fixture: the arcs_ij.gcode toolpath with G2/G3 pre-decomposed into",
    "; G1 chords at resolution 1.0 (generated by a planArc replica).",
    "; Exercises: equivalence between native arc decomposition and a",
    "; slicer emitting chords directly (arc fitting disabled).",
    "G90",
    "M82",
    "G92 E0",
    "G1 X10 Y0 Z0.4 F6000",
]

# G3 X0 Y10 I-10 E3 F1800  from (10,0,0.4) E0
lines, pos = plan_arc([10., 0., 0.4, 0.], [0., 10., 0.4], (-10., 0.), False,
                      3., 1800., True)
out += lines
out.append("G1 X20 Y10 F6000")
# G2 I-10 E9 F1800  from (20,10,0.4) E3, target = current (full circle)
lines, pos = plan_arc([20., 10., 0.4, 3.], [20., 10., 0.4], (-10., 0.), True,
                      9., 1800., True)
out += lines
# G3 X30 Y10 I5 F3600  from (20,10,0.4) E9, no E word
lines, pos = plan_arc([20., 10., 0.4, 9.], [30., 10., 0.4], (5., 0.), False,
                      None, 3600., True)
out += lines
out.append("G1 E8.5 F2100")

with open("fixtures/synthetic/arcs_prechorded.gcode", "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print(f"wrote {len(out)} lines")
